# Generated by Django 4.1.5 on 2023-01-09 13:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Почта"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="RU", verbose_name="Телефон"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                ("text", models.TextField(blank=True, verbose_name="Информация")),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Шаблоны",
            },
        ),
    ]
